pipeline {
    agent any

    tools {
        maven 'M2'
        jdk 'JAVA24'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                bat 'mvn.cmd clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    bat '''
                    mvn.cmd sonar:sonar ^
                    -Dsonar.projectKey=shreyas-org_jenkins-sonar ^
                    -Dsonar.projectName=Java-Microservices ^
                    -Dsonar.java.binaries=target
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build & SonarQube analysis completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
