version: '4'
services:
  mongodb:
    image: mongo:latest  # Use the latest image of MongoDB
    container_name: mongodb
    restart: unless-stopped  # Restart policy for the container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service  # Initial database to be created
    ports:
      - "8094:27017"  # Map container's port 27017 to host's port 8094
    volumes:
      - ./docker/mongodb/data:/data/db  # Persist MongoDB data
